### ISSUE TITLE
list of s3 files incomplete

### ISSUE THREAD

**Issue by parosen** [aivazis/qed#57]
With locator menu open, if the folder is an s3 bucket, qed attempts to list all files since there is no true folder structure supporting the hierarchy.  There must be a limit to the number that can be displayed, because it is not possible to scroll to the file of interest.

**Comment by aivazis** [comment]
Addressed in 1ad82358ff7a6a3ee11504a3e18e689674dd5cf6.

@parosen, do you mind checking that it works well enough close this issue?

**Comment by parosen** [comment]
I did check last night from my laptop, and it seems to work fine.  I also tried it on the ODS and I think it still crashes before being given the list.

**Comment by aivazis** [comment]
do you mind posting a screenshot of the archive connection form right before you hit connect? i'd like to try to diagnose

**Comment by parosen** [comment]
![screen](https://github.com/aivazis/qed/assets/38848289/1f1c39a8-ed00-4dd1-ae59-a47d60107c41)
Here's a screen shot before I hit connect.

**Comment by parosen** [comment]
Here's a screen shot after hitting "connect"
![screen_after](https://github.com/aivazis/qed/assets/38848289/5a0c9eef-f9c0-4b7b-af4e-fb6c31132ca9)

**Comment by aivazis** [comment]
i think the problem will go away if you turn your ~/.aws into a real directory instead of a symbolic link. can you try that and let me know?
